name: Node.js CI

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  UPLOADTHING_SECRET: ${{ secrets.UPLOADTHING_SECRET }}
  UPLOADTHING_APP_ID: ${{ secrets.UPLOADTHING_APP_ID }}

jobs:
  ci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run format:check
      - run: npm run typecheck
      - run: npm run lint
      - run: npm test